(()=>{
const REM='blocks-reminders-v1';
function bs(){try{return Array.isArray(blocks)?blocks:[]}catch(e){return[]}}
function rems(){try{return JSON.parse(localStorage.getItem(REM)||'[]')}catch(e){return[]}}
function active(){return bs().filter(b=>b.status!=='done')}
function esc(s){return typeof escapeHtml==='function'?escapeHtml(String(s??'')):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function latest(b){return (b.notes||[]).slice().sort((a,z)=>(z.editedTs||z.ts)-(a.editedTs||a.ts))[0]?.text||''}
function reason(b,type){if(type==='waiting')return b.waitingFor||b.smart?.waiting||latest(b);if(type==='attention')return b.nextAction||b.smart?.action||b.waitingFor||b.smart?.waiting||latest(b);return latest(b)}
function lists(){const a=active(),rs=rems().filter(r=>!r.done);return{attention:a.filter(b=>b.nextAction||b.smart?.action||b.waitingFor||b.smart?.waiting),waiting:a.filter(b=>b.waitingFor||b.smart?.waiting),reminders:rs,due:rs.filter(r=>r.when<=Date.now())}}
function fmt(ts){const d=new Date(ts);return d.toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
function complexGroups(){const m=new Map();bs().forEach(b=>{const name=(b.complex||'').trim();if(!name)return;if(!m.has(name))m.set(name,[]);m.get(name).push(b)});return m}
function syncComplexes(){let changed=false;complexGroups().forEach(children=>{const allDone=children.length>0&&children.every(b=>b.status==='done');children.forEach(b=>{if(allDone&&!b.complexCompleted){b.complexCompleted=true;b.complexCompletedAt=Date.now();changed=true}else if(!allDone&&b.complexCompleted){b.complexCompleted=false;delete b.complexCompletedAt;changed=true}})});if(changed&&typeof saveBlocks==='function')saveBlocks()}
function openBlock(id){closeOpsList();setTimeout(()=>{if(typeof openComplexChild==='function')openComplexChild(id);else{const b=bs().find(x=>String(x.id)===String(id));if(b&&typeof toggleBlock==='function')toggleBlock(id)}},180)}
window.openOpsBlock=openBlock;
window.openOpsList=function(kind){const data=lists(),items=data[kind]||[],title={attention:'Требуют внимания',waiting:'Ожидают',reminders:'Напоминания',due:'Просрочено'}[kind]||'Список';closeOpsList(true);const bg=document.createElement('div');bg.id='opsSheet';bg.className='ops-sheet-bg';let rows='';if(kind==='reminders'||kind==='due')rows=items.map(r=>{const b=bs().find(x=>String(x.id)===String(r.blockId));return `<button type="button" class="ops-item" data-block="${esc(b?.id||'')}"><b>${esc(b?.title||r.blockTitle||'Свободная заметка')}</b><span>${esc(r.text||r.source||'')}</span><small>🔔 ${fmt(r.when)}</small></button>`}).join('');else rows=items.map(b=>`<button type="button" class="ops-item" data-block="${esc(b.id)}"><b>${esc(b.title)}</b><span>${esc(reason(b,kind)||'Нет пояснения')}</span><small>${esc(b.currentState||b.smart?.place||'')}</small></button>`).join('');bg.innerHTML=`<div class="ops-sheet"><div class="ops-sheet-head"><b>${title} · ${items.length}</b><button type="button" class="ops-close">×</button></div><div class="ops-sheet-list">${rows||'<div class="ops-empty">Здесь пока ничего нет</div>'}</div></div>`;bg.querySelector('.ops-close').addEventListener('click',()=>closeOpsList());bg.querySelectorAll('.ops-item').forEach(row=>row.addEventListener('click',()=>{const id=row.dataset.block;if(id)openBlock(id)}));bg.addEventListener('click',e=>{if(e.target===bg)closeOpsList()});document.documentElement.appendChild(bg);requestAnimationFrame(()=>requestAnimationFrame(()=>bg.classList.add('show')))};
window.closeOpsList=function(immediate=false){const x=document.getElementById('opsSheet');if(!x)return;if(immediate){x.remove();return}x.classList.remove('show');setTimeout(()=>x.remove(),220)};
function patchDashboard(){const d=document.getElementById('persistentTodayDash')||document.getElementById('opsDash');if(!d)return;const c=lists(),cards=d.querySelectorAll('.ops-dash-cards button');const vals=[c.attention.length,c.waiting.length,c.reminders.length,c.due.length],k=['attention','waiting','reminders','due'];cards.forEach((b,i)=>{if(!k[i])return;const n=b.querySelector('b');if(n)n.textContent=vals[i];b.dataset.opsKind=k[i];b.title='Нажми, чтобы посмотреть список'})}
function hideDoneFromAll(){let sf='all';try{sf=statusFilter}catch(e){}if(sf!=='all')return;document.querySelectorAll('.card').forEach(card=>{const text=card.textContent||'',b=bs().find(x=>x.title&&text.includes(x.title));if(b?.status==='done')card.style.display='none'});const n=active().length;document.querySelectorAll('.tab,.rchip').forEach(el=>{if(/^\s*Все\s*[·•]/i.test(el.textContent||''))el.textContent=(el.textContent||'').replace(/([·•])\s*\d+/,'$1 '+n)})}
function patchComplexes(){const groups=complexGroups();document.querySelectorAll('.cx-card').forEach(card=>{const head=card.querySelector('.cx-head');if(!head)return;const txt=head.textContent||'';let match=null;for(const [name,ch] of groups){if(txt.includes(name)){match={name,ch};break}}if(!match)return;const done=match.ch.filter(b=>b.status==='done').length,all=match.ch.length,allDone=all>0&&done===all;card.classList.toggle('cx-completed',allDone);const strong=head.querySelector('strong');if(strong)strong.textContent=allDone?'✓ Завершён':`${done}/${all}`});const title=[...document.querySelectorAll('.cx-section-title')].find(x=>/комплекс/i.test(x.textContent||''));if(title)title.textContent=`Комплексы ${[...groups.values()].filter(ch=>!ch.every(b=>b.status==='done')).length}`}
function tick(){syncComplexes();hideDoneFromAll();patchComplexes();patchDashboard()}
document.addEventListener('click',e=>{const card=e.target.closest?.('[data-ops-kind]');if(card){e.preventDefault();e.stopPropagation();openOpsList(card.dataset.opsKind);return}setTimeout(tick,80)},true);
new MutationObserver(()=>{clearTimeout(window.__awu);window.__awu=setTimeout(tick,25)}).observe(document.body,{childList:true,subtree:true});setInterval(tick,700);tick();
})();