(()=>{
const icon=p=>`<svg viewBox="0 0 24 24" aria-hidden="true">${p}</svg>`,searchIcon=icon('<circle cx="11" cy="11" r="6.5"></circle><path d="m16 16 4 4"></path>'),noteIcon=icon('<path d="M4 20h4l11-11a2.8 2.8 0 0 0-4-4L4 16v4Z"></path><path d="m13.5 6.5 4 4"></path>'),plusIcon=icon('<path d="M12 5v14M5 12h14"></path>');
const dock=document.querySelector('.dock');if(dock){const b=dock.querySelectorAll('.dock-circle');if(b[0])b[0].innerHTML=searchIcon;if(b[1])b[1].innerHTML=noteIcon;if(b[2])b[2].innerHTML=plusIcon}
const applyTheme=m=>{document.body.classList.toggle('dark',m==='dark');localStorage.setItem('blocks-theme',m);const t=document.querySelector('.theme-toggle');if(t)t.textContent=m==='dark'?'☀︎':'☾'},savedTheme=localStorage.getItem('blocks-theme')||((window.matchMedia&&matchMedia('(prefers-color-scheme: dark)').matches)?'dark':'light'),theme=document.createElement('button');theme.className='theme-toggle';theme.type='button';theme.setAttribute('aria-label','Переключить тему');theme.onclick=()=>applyTheme(document.body.classList.contains('dark')?'light':'dark');document.body.appendChild(theme);applyTheme(savedTheme);
window.deleteBlock=function(id){const b=blocks.find(x=>x.id===id);if(!b)return;if(!confirm(`Удалить блок «${b.title}»?\n\nЗаметки внутри блока тоже будут удалены.`))return;blocks=blocks.filter(x=>x.id!==id);openIds.delete(id);saveBlocks();renderAll();showToast('Блок удалён')};
function ensure(b){if(b.currentState===undefined)b.currentState='';if(b.waitingFor===undefined)b.waitingFor='';if(b.nextAction===undefined)b.nextAction='';if(b.controlDate===undefined)b.controlDate='';if(b.flowHistory===undefined)b.flowHistory=[];if(b.smart===undefined)b.smart={}}
blocks.forEach(ensure);const originalSave=window.saveBlocks;window.saveBlocks=function(){blocks.forEach(ensure);return originalSave()};
const placeRules=[['Слесарка',/слесарк/i],['Склад',/склад/i],['ОТК',/\bотк\b/i],['ВП',/\bвп\b/i],['ВН',/\bвн\b|у вн/i],['Сектор',/сектор/i],['Покраска',/покраск|красим/i],['Сборка',/сборк|собрать/i],['Испытания',/испытан|климат/i],['Отгрузка',/отгруз/i]];
function smartParse(text){text=(text||'').trim();const r={source:text,place:'',waiting:'',action:'',flags:[]};for(const [n,re] of placeRules)if(re.test(text)){r.place=n;break}const w=text.match(/(?:жд[её]м|ждать|ожида(?:ем|ть)?)[\s:,-]+([^\n.!?]+)/i);if(w)r.waiting=w[1].trim().slice(0,90);else if(/нет\s+(?:распоряжения|детал|плат|транзистор|документ|рс\b)/i.test(text)){const m=text.match(/нет\s+([^\n.!?]+)/i);if(m)r.waiting=m[1].trim().slice(0,90)}const lines=text.split(/\n+/).map(x=>x.trim()).filter(Boolean);const act=lines.find(x=>/(надо|нужно|отнести|отдать|заказать|дозаказать|проверить|чекнуть|позвонить|узнать|составить|раскидать|передать|вернуть|забрать)/i.test(x)&&!/(готово|передал|составил)$/i.test(x));if(act)r.action=act.slice(0,130);if(/дефект|деф\./i.test(text))r.flags.push('Дефект');if(/паспорт|протокол|акт|тз\b|спецификац|док/i.test(text))r.flags.push('Документы');if(/готово|сдан|отгружен|восстановлен/i.test(text))r.flags.push('Есть результат');return r}
function refreshSmart(b){ensure(b);const n=(b.notes||[]).slice().sort((a,z)=>(z.editedTs||z.ts)-(a.editedTs||a.ts))[0];if(!n){b.smart={};return}const p=smartParse(n.text);b.smart={...p,ts:n.editedTs||n.ts};if(p.place)b.currentState=p.place;if(p.waiting)b.waitingFor=p.waiting;if(p.action)b.nextAction=p.action}
blocks.forEach(b=>{if((b.notes||[]).length)refreshSmart(b)});
const oldSubmit=window.submitNote;window.submitNote=function(){const bid=noteCtx&&noteCtx.blockId;oldSubmit();if(bid&&bid!=='FREE'){const b=blocks.find(x=>x.id===bid);if(b){refreshSmart(b);saveBlocks();renderAll()}}};
window.setOpsField=function(id,key,val){const b=blocks.find(x=>x.id===id);if(!b)return;ensure(b);const old=b[key]||'';val=(val||'').trim();if(old===val)return;b[key]=val;b.updatedAt=Date.now();saveBlocks();renderAll()};
function smartSummary(b){ensure(b);const s=b.smart||{},chips=[];if(s.place)chips.push(`<span class="smart-chip">📍 ${escapeHtml(s.place)}</span>`);if(s.waiting)chips.push(`<span class="smart-chip wait">⏳ ${escapeHtml(s.waiting)}</span>`);if(s.action)chips.push(`<span class="smart-chip action">⚡ ${escapeHtml(s.action)}</span>`);return chips.length?`<div class="smart-summary">${chips.join('')}</div>`:''}
const oldBuild=window.buildCardHtml;window.buildCardHtml=function(b){ensure(b);let h=oldBuild(b);h=h.replace('<div class="card-body">',smartSummary(b)+'<div class="card-body">');const panel=`<div class="ops-panel smart-panel"><div class="fieldlabel">Авторазбор последней заметки</div><div class="smart-help">Пиши как обычно. Приложение само пытается выделить местонахождение, ожидание и следующее действие. Если ошиблось — исходная заметка остаётся без изменений.</div>${b.smart?.source?smartSummary(b):'<div class="smart-empty">Добавь заметку — здесь появится краткая выжимка.</div>'}</div>`;h=h.replace('<div class="fieldlabel">Категория</div>',panel+'<div class="fieldlabel">Категория</div>');return h};
const oldRender=window.renderList;window.renderList=function(){const inp=document.getElementById('search'),q=(inp?.value||'').trim().toLowerCase();if(!q)return oldRender();const saved=blocks,filtered=saved.filter(b=>{if(statusFilter!=='all'&&b.status!==statusFilter)return false;if(categoryFilter!=='all'&&b.category!==categoryFilter)return false;ensure(b);const cat=CAT_MAP[b.category]?.label||'',notes=(b.notes||[]).map(n=>n.text).join(' ');return[b.title,cat,b.complex,b.role,notes,b.currentState,b.waitingFor,b.nextAction].join(' ').toLowerCase().includes(q)});blocks=filtered;try{oldRender()}finally{blocks=saved}};
function complexDashboard(){const main=document.getElementById('main');if(!main||document.getElementById('complexDash'))return;const groups={};blocks.filter(b=>b.complex&&b.status!=='done').forEach(b=>(groups[b.complex]??=[]).push(b));const list=Object.entries(groups).filter(([,a])=>a.length>1).sort((a,b)=>b[1].length-a[1].length);if(!list.length)return;const el=document.createElement('section');el.id='complexDash';el.className='complex-dash';el.innerHTML=`<div class="complex-dash-title">Комплексы</div>${list.slice(0,6).map(([name,arr])=>{const done=arr.filter(x=>x.status==='done').length;return `<button class="complex-row" onclick="document.getElementById('search').value=${JSON.stringify(name)};renderList();document.getElementById('search').scrollIntoView({behavior:'smooth',block:'center'})"><span><b>${escapeHtml(name)}</b><small>${arr.length} блоков</small></span><strong>${done}/${arr.length}</strong></button>`}).join('')}`;main.prepend(el)}
function attentionDashboard(){const main=document.getElementById('main');if(!main||document.getElementById('opsDash'))return;const active=blocks.filter(b=>b.status!=='done'),attention=active.filter(b=>{ensure(b);return b.smart?.action||b.smart?.waiting}),waiting=active.filter(b=>b.smart?.waiting),stale=active.filter(b=>Date.now()-(b.updatedAt||0)>3*864e5);const el=document.createElement('div');el.id='opsDash';el.className='ops-dash';el.innerHTML=`<div class="ops-dash-title">Сегодня</div><div class="ops-dash-cards"><button><b>${attention.length}</b><span>требуют внимания</span></button><button><b>${waiting.length}</b><span>ожидают</span></button><button><b>${active.length}</b><span>активных</span></button><button><b>${stale.length}</b><span>без движения 3д+</span></button></div></div>`;main.prepend(el)}
const baseRenderAll=window.renderAll;window.renderAll=function(){baseRenderAll();attentionDashboard();complexDashboard()};const input=document.getElementById('search');if(input)input.placeholder='Поиск: блок, комплекс, действие, заметка';saveBlocks();renderAll();
})();